services:

  app:
    image: rsu_project:latest
    container_name: rsu_project
    ports:
      - "8000:8000" 
    networks:
      - rsu_network
    volumes:
      - ./app:/var/www/html  
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=rsu_project 
      - DB_USERNAME=root
      - DB_PASSWORD=12345
    depends_on:
      - mysql


  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - rsu_network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"  


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"  
    networks:
      - rsu_network

networks:
  rsu_network:
    driver: bridge

volumes:
  mysql_data: